DROP DATABASE IF EXISTS Sipsewana;
CREATE DATABASE IF NOT EXISTS Sipsewana;
SHOW DATABASES ;
USE Sipsewana;

DROP TABLE IF EXISTS Student;
CREATE TABLE IF NOT EXISTS Student(
    sId VARCHAR (15),
    sName VARCHAR(45) NOT NULL DEFAULT 'Unknown',
    nic VARCHAR (20),
    address TEXT,
    contact VARCHAR (15),
    program VARCHAR (30),
    CONSTRAINT PRIMARY KEY (sId)
    );
SHOW TABLES ;
DESCRIBE Student;

DROP TABLE IF EXISTS Program;
CREATE TABLE IF NOT EXISTS Program(
    pId VARCHAR(15),
    pName VARCHAR(45) NOT NULL DEFAULT 'Unknown',
    duration VARCHAR (15),
    fee DOUBLE ,
    CONSTRAINT PRIMARY KEY (pId)
    );
SHOW TABLES ;
DESCRIBE Program;

DROP TABLE IF EXISTS `Register Detail`;
CREATE TABLE IF NOT EXISTS `Register Detail`(
    sId VARCHAR (15),
    pId VARCHAR(15),
    date VARCHAR (10),
    CONSTRAINT PRIMARY KEY (sId,pId),
    CONSTRAINT FOREIGN KEY (sId) REFERENCES Student(sId) ON DELETE CASCADE ON UPDATE CASCADE ,
    CONSTRAINT FOREIGN KEY (pId) REFERENCES Program(pId) ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES ;
DESCRIBE `Register Detail`;
